set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {ad_ch2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch1[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[13]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[12]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[11]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[10]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[9]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[8]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[7]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[6]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[5]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[4]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[3]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[2]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[1]}]
set_property IOSTANDARD LVCMOS33 [get_ports {da_ch2[0]}]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk_ch1]
set_property IOSTANDARD LVCMOS33 [get_ports da_wrt_ch1]
set_property IOSTANDARD LVCMOS33 [get_ports clk]
set_property IOSTANDARD LVCMOS33 [get_ports rst_n]
set_property IOSTANDARD LVCMOS33 [get_ports da_wrt_ch2]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk_ch2]
set_property IOSTANDARD LVCMOS33 [get_ports ad_clk_ch2]
set_property IOSTANDARD LVCMOS33 [get_ports da_clk_ch1]
set_property PACKAGE_PIN U18 [get_ports clk]
set_property PACKAGE_PIN N15 [get_ports rst_n]
set_property PACKAGE_PIN K19 [get_ports da_clk_ch1]
set_property PACKAGE_PIN J19 [get_ports da_wrt_ch1]
set_property PACKAGE_PIN H20 [get_ports da_clk_ch2]
set_property PACKAGE_PIN J20 [get_ports da_wrt_ch2]
set_property PACKAGE_PIN W19 [get_ports ad_clk_ch2]
set_property PACKAGE_PIN T10 [get_ports ad_clk_ch1]
set_property PACKAGE_PIN K17 [get_ports {da_ch1[0]}]
set_property PACKAGE_PIN K18 [get_ports {da_ch1[1]}]
set_property PACKAGE_PIN M19 [get_ports {da_ch1[2]}]
set_property PACKAGE_PIN M20 [get_ports {da_ch1[3]}]
set_property PACKAGE_PIN L19 [get_ports {da_ch1[4]}]
set_property PACKAGE_PIN L20 [get_ports {da_ch1[5]}]
set_property PACKAGE_PIN J18 [get_ports {da_ch1[6]}]
set_property PACKAGE_PIN H18 [get_ports {da_ch1[7]}]
set_property PACKAGE_PIN G19 [get_ports {da_ch1[8]}]
set_property PACKAGE_PIN G20 [get_ports {da_ch1[9]}]
set_property PACKAGE_PIN F19 [get_ports {da_ch1[10]}]
set_property PACKAGE_PIN F20 [get_ports {da_ch1[11]}]
set_property PACKAGE_PIN F16 [get_ports {da_ch1[12]}]
set_property PACKAGE_PIN F17 [get_ports {da_ch1[13]}]
set_property PACKAGE_PIN H15 [get_ports {da_ch2[0]}]
set_property PACKAGE_PIN G15 [get_ports {da_ch2[1]}]
set_property PACKAGE_PIN H16 [get_ports {da_ch2[2]}]
set_property PACKAGE_PIN H17 [get_ports {da_ch2[3]}]
set_property PACKAGE_PIN G17 [get_ports {da_ch2[4]}]
set_property PACKAGE_PIN G18 [get_ports {da_ch2[5]}]
set_property PACKAGE_PIN L17 [get_ports {da_ch2[13]}]
set_property PACKAGE_PIN L16 [get_ports {da_ch2[12]}]
set_property PACKAGE_PIN M18 [get_ports {da_ch2[11]}]
set_property PACKAGE_PIN M17 [get_ports {da_ch2[10]}]
set_property PACKAGE_PIN D20 [get_ports {da_ch2[9]}]
set_property PACKAGE_PIN D19 [get_ports {da_ch2[8]}]
set_property PACKAGE_PIN E19 [get_ports {da_ch2[7]}]
set_property PACKAGE_PIN E18 [get_ports {da_ch2[6]}]
set_property PACKAGE_PIN T16 [get_ports {ad_ch1[0]}]
set_property PACKAGE_PIN U17 [get_ports {ad_ch1[1]}]
set_property PACKAGE_PIN V17 [get_ports {ad_ch1[2]}]
set_property PACKAGE_PIN V18 [get_ports {ad_ch1[3]}]
set_property PACKAGE_PIN T14 [get_ports {ad_ch1[4]}]
set_property PACKAGE_PIN T15 [get_ports {ad_ch1[5]}]
set_property PACKAGE_PIN U13 [get_ports {ad_ch1[6]}]
set_property PACKAGE_PIN V13 [get_ports {ad_ch1[7]}]
set_property PACKAGE_PIN V12 [get_ports {ad_ch1[8]}]
set_property PACKAGE_PIN W13 [get_ports {ad_ch1[9]}]
set_property PACKAGE_PIN T12 [get_ports {ad_ch1[10]}]
set_property PACKAGE_PIN U12 [get_ports {ad_ch1[11]}]
set_property PACKAGE_PIN W18 [get_ports {ad_ch2[0]}]
set_property PACKAGE_PIN R14 [get_ports {ad_ch2[1]}]
set_property PACKAGE_PIN P14 [get_ports {ad_ch2[2]}]
set_property PACKAGE_PIN Y17 [get_ports {ad_ch2[3]}]
set_property PACKAGE_PIN Y16 [get_ports {ad_ch2[4]}]
set_property PACKAGE_PIN W15 [get_ports {ad_ch2[5]}]
set_property PACKAGE_PIN V15 [get_ports {ad_ch2[6]}]
set_property PACKAGE_PIN Y14 [get_ports {ad_ch2[7]}]
set_property PACKAGE_PIN W14 [get_ports {ad_ch2[8]}]
set_property PACKAGE_PIN P18 [get_ports {ad_ch2[9]}]
set_property PACKAGE_PIN N17 [get_ports {ad_ch2[10]}]
set_property PACKAGE_PIN U15 [get_ports {ad_ch2[11]}]

# The DDC/ADC processing clock and the PS FCLK are generated from different
# sources in this design. Data crosses this boundary through AXIS async FIFO or
# explicit synchronizers/debug-only status sampling, so do not time these two
# domains as related clocks.
set_clock_groups -asynchronous \
    -group [get_clocks clk_out1_design_1_clk_wiz_0_0] \
    -group [get_clocks clk_fpga_0]

# AXI-Lite control registers are written in the PS FCLK domain and sampled by
# ddc_tune_axi_lite in the 65 MHz DDC domain. The update strobe is synchronized
# separately, so these data/strobe crossings are intentional CDC paths.
set_false_path \
    -from [get_cells -hier -regexp {.*ddc_tune_axi_lite_i/phase_inc_axi_reg\[[0-9]+\]}] \
    -to   [get_cells -hier -regexp {.*ddc_tune_axi_lite_i/phase_meta_reg\[[0-9]+\]}]

set_false_path \
    -from [get_cells -hier -regexp {.*ddc_tune_axi_lite_i/phase_toggle_axi_reg}] \
    -to   [get_cells -hier -regexp {.*ddc_tune_axi_lite_i/phase_toggle_meta_reg}]

set_false_path \
    -from [get_cells -hier -regexp {.*ddc_tune_axi_lite_i/clear_toggle_axi_reg}] \
    -to   [get_cells -hier -regexp {.*ddc_tune_axi_lite_i/clear_toggle_meta_reg}]

# DDC debug/status counters are sampled by the PS AXI-Lite clock domain for
# software visibility only. They are not used to control DDC data movement.
set_false_path \
    -from [get_cells -hier -regexp {.*ddc_ip_axis_source_i/(packet_count|clip_count|fifo_full_seen|axis_stall_seen|clip_seen|iq_fifo_count|iq_fifo_max_seen).*}] \
    -to   [get_cells -hier -regexp {.*ddc_tune_axi_lite_i/(status_meta|counters_meta)_reg.*}]
